In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [2]:
# Read datasets

df_olympic_hosts = pd.read_csv("../data/raw/olympic_hosts.csv")
display(df_olympic_hosts.head())

df_olympic_medals = pd.read_csv("../data/raw/olympic_medals.csv")
display(df_olympic_medals.head())

df_paris_medallists = pd.read_csv("../data/raw/paris_medallists.csv")
display(df_paris_medallists.head())

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

,medal_date,medal_type,medal_code,name,gender,country_code,country,country_long,nationality_code,nationality,...,team,team_gender,discipline,event,event_type,url_event,birth_date,code_athlete,code_team,is_medallist
0,2024-07-27,Gold Medal,1.0,EVENEPOEL Remco,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,2000-01-25,1903136,NaN,True
1,2024-07-27,Silver Medal,2.0,GANNA Filippo,Male,ITA,Italy,Italy,ITA,Italy,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1996-07-25,1923520,NaN,True
2,2024-07-27,Bronze Medal,3.0,van AERT Wout,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1994-09-15,1903147,NaN,True
3,2024-07-27,Gold Medal,1.0,BROWN Grace,Female,AUS,Australia,Australia,AUS,Australia,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1992-07-07,1940173,NaN,True
4,2024-07-27,Silver Medal,2.0,HENDERSON Anna,Female,GBR,Great Britain,Great Britain,GBR,Great Britain,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1998-11-14,1912525,NaN,True

In [3]:
# Olympic hosts - filter by game_season, game_year, game_location

# Olympic medals - discipline_title, medal_type, country_name, slug_game

# Olympic medallists - medal_date (using only year), medal_type, medal_code, gender, country_code, country, discipline, is_medallist

In [11]:
# Clean olympic hosts:
df_olympic_hosts.columns

# Drop columns (game_end_date, game_start_date)
df_olympic_hosts_clean = df_olympic_hosts.drop(['game_end_date', 'game_start_date'], axis=1)

# Filter for summer games
df_olympic_hosts_clean = df_olympic_hosts_clean[df_olympic_hosts_clean['game_season'] == 'Summer']

# split game_slug
df_olympic_hosts_clean['game_slug'] = df_olympic_hosts_clean['game_slug'].str.split('-')

#column_split = df_olympic_hosts_clean['game_slug'].str.split('-')

df_olympic_hosts_clean['location'] = df_olympic_hosts_clean['game_slug'].str[0]
df_olympic_hosts_clean['year'] = df_olympic_hosts_clean['game_slug'].str[1]

df_olympic_hosts_clean.head()

,game_slug,game_location,game_name,game_season,game_year,location,year
1,"[tokyo, 2020]",Japan,Tokyo 2020,Summer,2020,tokyo,2020
3,"[rio, 2016]",Brazil,Rio 2016,Summer,2016,rio,2016
5,"[london, 2012]",Great Britain,London 2012,Summer,2012,london,2012
7,"[beijing, 2008]",China,Beijing 2008,Summer,2008,beijing,2008
9,"[athens, 2004]",Greece,Athens 2004,Summer,2004,athens,2004

In [ ]:
# Clean olympic medals (discipline_title, medal_type, country_name, slug_game
df_olympic_medals.columns

df_olympic_medals_clean = df_olympic_medals.drop(['event_title', 'event_gender', 'participant_type', 'participant_title', 'athlete_url',
       'athlete_full_name', 'country_3_letter_code'], axis = 1)
df_olympic_medals_clean